# Generated by Django 5.0 on 2025-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptiontier_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
