# Generated by Django 5.0 on 2025-05-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
