# Generated by Django 5.0 on 2025-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
